apiVersion: v1
entries:
  centos-centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T17:49:12.797248158-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 94619a263900939def63a1c771603c666458fa0161394616a26ce503c085f22f
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T17:49:12.797443981-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 41753fb6dec3edfc45207a11444c5649dd978906363b530783dbc27c0a65b8d1
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T17:49:12.797827138-04:00"
    description: Simple go app to showcase cert-manager intergration
    digest: edd7d42908dcdcd18b3742f313914e8605846f7152359b897a6fb88daa0a2312
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-17T17:49:12.797968769-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: eca9a95d67cdc40bd6cc9c379f30e799685c4dcf68cc2aad66c4e73cc6d17f8c
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-17T17:49:12.796974333-04:00"
