apiVersion: v1
entries:
  centos-simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-21T19:57:03.591833754-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 3eaac22a94adab4afcb8b3b54d80ad1deb0e9842e0ae9257fe803af3fbe8ddd4
    icon: https://avatars.githubusercontent.com/u/55542927
    name: centos-simple-kmod
    type: application
    urls:
    - file:///charts/example/centos-simple-kmod-0.0.1.tgz
    version: 0.0.1
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-21T19:57:03.592248002-04:00"
    description: Simple go app to showcase cert-manager intergration
    digest: f3d9f9538ea0f6a2ebdcfaa49d541fbe605599e2978eb13b25b45ed470cf8b87
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-21T19:57:03.59240747-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 5520bf9ff850f0c5d1b0d5d735c2f1da4edab303c76b511208e3d49119507f4d
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-21T19:57:03.59095003-04:00"
